import os

os.mkdir('plots')
os.mkdir('results')
os.mkdir('results/mle')
os.mkdir('results/mle/myopic_stupid')
os.mkdir('results/mle/myopic')
os.mkdir('results/mle/historical')
os.mkdir('results/e2e')
os.mkdir('results/e2e/opl_relu')
os.mkdir('results/e2e/opl_softplus')
os.mkdir('results/e2e/opl_relu/myopic')
os.mkdir('results/e2e/opl_relu/myopic_stupid')
os.mkdir('results/e2e/opl_softplus/myopic')
os.mkdir('results/e2e/opl_softplus/myopic_stupid')
os.mkdir('results/e2e/opl_relu/historical')
os.mkdir('results/e2e/opl_softplus/historical')
os.mkdir('results/e2e/cal')
os.mkdir('results/e2e/cal/myopic')
os.mkdir('results/e2e/cal/myopic_stupid')
os.mkdir('results/e2e/cal/historical')
